name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login ghcr.io
      run : |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.USERNAME}} --password-stdin
    - name: Build the Docker image
      run: |
        export VERSION=`node -p "require('.backend/package.json').version"`-dev
        export NAME=`node -p "require('.backend/package.json').name"`
        docker build . --file .backend/Dockerfile --tag $NAME:$VERSION
        docker push ghcr.io/bryantpirih/$NAME:$VERSION
        export VERSION_FE=`node -p "require('.frontend/package.json').version"`-dev
        export NAME_FE=`node -p "require('.frontend/package.json').name"`
        docker build . --file .frontend/Dockerfile --tag $NAME_FE:$VERSION_FE
        docker push ghcr.io/bryantpirih/$NAME_FE:$VERSION_FE
    - name: docker logout ghcr.io
      run: |
        docker logout ghcr.io
        
